name: Docker Build CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Make gradlew executable
        run: chmod +x gradlew
        working-directory: contents/cicd.demo

      - name: Build Docker image
        run: docker build -t my-spring-app .
        working-directory: contents/cicd.demo

      - name: Verify image
        run: docker images
